# Generated by Django 5.2.12 on 2026-03-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
