# Generated by Django 5.2.12 on 2026-03-09 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidate_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='score',
        ),
    ]
